<?php
return array(
    //Settings
        //layout
            'pg_postLayoutColumns' => 3,
            'pg_postLayoutColumnsTablet' => 2,
            'pg_postLayoutColumnsMobile' => 2,
            'pg_numberOfRow' => 2,
            'pg_numberOfRowTablet' => 2,
            'pg_numberOfRowMobile' => 2,
            'pg_posts' => [],
            'postsPerPage' => 6,
            'currentPage' => 1,
            'pg_postLayoutColumns' => 3,
            'pg_postLayoutColumnsTablet' => 2,
            'pg_postLayoutColumnsMobile' => 1,
            'pg_numberOfRow' => 2,
            'pg_numberOfRowTablet' => 2,
            'pg_numberOfRowMobile' => 2,
            'id' => '',
            'uniqueID' => '',
        //filter
            'sortByOrder'=> "desc",
            'sortByField' => "date",
        //layoutcontrols
            'pg_featuredimage_animate' => true,
            'pg_FullContent' => 'default',
            'pg_FullContentTablet' => 'default',
            'pg_FullContentMobile' => 'default',
            'pg_FeaturedImage' => 'default',
            'pg_FeaturedImageTablet' => 'default',
            'pg_FeaturedImageMobile' => 'default',
            'pg_Categories' => 'default',
            'pg_CategoriesTablet' => 'default',
            'pg_CategoriesMobile' => 'default',
            'pg_Author' => 'default',
            'pg_AuthorTablet' => 'default',
            'pg_AuthorMobile' => 'default',
            'pg_Date' => 'default',
            'pg_DateTablet' => 'default',
            'pg_DateMobile' => 'default',
            'pg_Tag' => 'default',
            'pg_TagTablet' => 'default',
            'pg_TagMobile' => 'default',
            'pg_numberOfCategories' => 1,
            'pg_featuredImageOnly' => false,
            'layoutColumnsType' => 'default',
            'layoutColumnsTypeTablet' => 'default',
            'layoutColumnsTypeMobile' => 'default',
            'pg_excerptSelector' => 'Read More',
            'pg_excerptWords' => 15,
            'pg_numberOfTags' => 1,
            'selectedCategories' => [],
            'pg_selectedCategory' => 0,
            'pg_selectedTag' => '',
            'expertview' => array(
                'Desktop'=> false,
                'Tablet' => false,
                'Mobile' => false,
            ),
            'fullContent'=> array(
                'Desktop'=> false,
                'Tablet' => false,
                'Mobile' => false,
            ),
            'featuredImage'=> array(
                'Desktop'=> true,
                'Tablet' => true,
                'Mobile' => true,
            ),
            'categori'=> array(
                'Desktop'=> true,
                'Tablet' => true,
                'Mobile' => true,
            ),
            'auth'=> array(
                'Desktop'=> false,
                'Tablet' => false,
                'Mobile' => false,
            ),
            'date' => array(
                'Desktop'=> false,
                'Tablet' => false,
                'Mobile' => false,
            ),
            'Showtag' => array(
                'Desktop'=> false,
                'Tablet' => false,
                'Mobile' => false,
            ),
            'Excerpt' => 'default',
            'ExcerptTablet' => 'default',
            'ExcerptMobile' => 'default',
            'pg_excerptWordsTablet' => 15,
            'pg_excerptWordsMobile' => 15,
            'Excerptnumber' => 'default',
            'ExcerptnumberTablet' => 'default',
            'ExcerptnumberMobile' => 'default',
            'pg_excerptSelectorTablet' => '',
            'pg_excerptSelectorMobile' => '',
            'ExcerptSelector' => 'default',
            'ExcerptSelectorTablet' => 'default',
            'ExcerptSelectorMobile' => 'default',
            'pg_showcategoriesMenu' => false,
            'pg_showTagsMenu' => false,
            'pg_showAuthorMenu' => false,

        //pagination
            'showpagination' => true,
            'pg_Paginationalignment'=> array(
                'Desktop'=> 'center',
                'Tablet'=> 'center',
                'Mobile'=> 'center'
            ),
            'pg_PaginationColor' => 'black',
            'pg_PaginationactiveColor' => 'black',
            'pg_paginationBorderRadius' => 10,
            'pg_showPaginationBorderColorMenu' => false,
            'pg_showPaginationBorderTypeMenu' => false,
            'pg_showPaginationBorderRadiusMenu' => false,
            'pg_showPaginationBorderSizeMenu' => false,
            'pg_PaginationbackgroundType' => 'color',
            'pg_PaginationbackgroundColor' => 'transparent',
            'pg_PaginationbackgroundGradient' => 'linear-gradient(135deg,#12c2e9 0%,#c471ed 50%,#f64f59 100%)',
            'paginationborderRadius' => "1px",
            'paginationpaddingborderRadius' => "1",
            'paginationborderRadius' => "1px",
            "pg_layoutalignment" => array(),
            'layoutbackground' => array(
                'type'=> 'color',
                'color'=> '#edebeb'
            ),
            'column'=>array(
                'Desktop'=>3,
                'Tablet'=>3,
                'Mobile'=>3
            ),
            'row'=> array(
                'Desktop'=>2,
                'Tablet'=>2,
                'Mobile'=>2
            ),      

    //Style
        //layout
            'layoutcustomWidth' => '100%',
            'layoutcustomWidthTablet' => '100%',
            'layoutcustomWidthMobile' => '100%',
            'layoutcustomWidthUnit' => '%',
            'pg_backgroundColor' => '#F6F6F6',
            'pg_backgroundType' => 'solid',
            'pg_blockTitleColor' => '#333',
            'pg_blockTitleSize' => 200,
            'pg_blockTitleTag' => 'h2',
            'pg_postBorderRadius' => "5",
            'buttonpaddingUnit' => 'px',
            'layout_backgroundType' => 'color',
            'layout_backgroundColor' => '#F6F6F6',
            'layout_backgroundImage' => '',
            'layout_backgroundGradient' => 'linear-gradient(135deg,#12c2e9 0%,#c471ed 50%,#f64f59 100%)',
            'layout_backgroundPosition' => null,
            'layout_backgroundAttachment' => 'scroll',
            'layout_backgroundRepeat' => 'no-repeat',
            'layout_backgroundSize' => 'cover',
            'pg_buttonpaddingTop' => 15,
        //title
            'pg_textColor' => '#121212b3',
            'pg_TitlelineHeight' => 1.6,
            'pg_TitleColor' => '#646464',
            'titlechoice' => 'color',
            'pg_TitleColorhvr' => 'blue',
            'titlechoicehvr' => 'color',
        //category
            'pg_categoryBackgroundColor' => '#000000',
            'pg_categoryTextColor' => '#D3D3D3',
            'category_backgroundType' => 'color',
            'category_backgroundColor' => 'black',
            'category_backgroundImage' => null,
            'category_backgroundGradient' => 'linear-gradient(135deg,#12c2e9 0%,#c471ed 50%,#f64f59 100%)',
        //tags
            'pg_tagBackgroundColor' => '#000000',
            'pg_tagTextColor' => '#808080',
            'tag_backgroundType' => 'color',
            'tag_backgroundColor' => '',
            'tag_backgroundImage' => null,
            'tag_backgroundGradient' => 'linear-gradient(135deg,#12c2e9 0%,#c471ed 50%,#f64f59 100%)',
        //author
            'pg_authorImageScale' => 0.6,
            'pg_authorTextColor' => 'gray',
            'pg_authorTextSize' => 14,
            'pg_authorTextSizeTablet' => 14,
            'pg_authorTextSizeMobile' => 14,
        //date
            'pg_dateTextSize' => 14,
            'pg_dateTextSizeTablet' => 14,
            'pg_dateTextSizeMobile' => 14,
            'pg_showDateMenu' => false,
            'classNamemain' => '',

            'layoutpadding' => array(
                'Desktop' => array(
                    'top' => 'var:preset|vayu-blocks-spacing|10',
                    'right' => 'var:preset|vayu-blocks-spacing|10',
                    'bottom' => 'var:preset|vayu-blocks-spacing|10',
                    'left' => 'var:preset|vayu-blocks-spacing|10',
                ),
                'Tablet' => array(
                    'top' => 'var:preset|vayu-blocks-spacing|10',
                    'right' => 'var:preset|vayu-blocks-spacing|10',
                    'bottom' => 'var:preset|vayu-blocks-spacing|10',
                    'left' => 'var:preset|vayu-blocks-spacing|10',
                ),
                'Mobile' => array(
                    'top' => 'var:preset|vayu-blocks-spacing|10',
                    'right' => 'var:preset|vayu-blocks-spacing|10',
                    'bottom' => 'var:preset|vayu-blocks-spacing|10',
                    'left' => 'var:preset|vayu-blocks-spacing|10',
                ),
            ),
            'pg_Paginationalignment' => array(
                'Desktop' => 'center',
                'Tablet' => 'center',
                'Mobile' => 'center',
            ),
            'titletypography' => array(
                'appearance' => array(
                    'Desktop' => array(
                        'key' => 'medium',
                        'name' => 'Medium',
                        'style' => array('fontWeight' => '500'),
                    ),
                    'Tablet' => array(
                        'key' => 'medium',
                        'name' => 'Medium',
                        'style' => array('fontWeight' => '500'),
                    ),
                    'Mobile' => array(
                        'key' => 'medium',
                        'name' => 'Medium',
                        'style' => array('fontWeight' => '500'),
                    ),
                ),
                'decoration' => array(),
                'fontSize' => array('Desktop' => '20px', 'Tablet' => '20px', 'Mobile' => '20px'),
                'fonts' => array(),
                'letterCase' => array(),
                'letterSpacing' => array(),
                'lineHeights' => array('Desktop' => '1', 'Tablet' => '1', 'Mobile' => '1'),
                'orientation' => array(),
            ),

            'exceColor'=>'#121212b3',
            'exceColorhvr'=> '',
            'excetypography' => array(
                'appearance' => array(),
                'decoration' => array(),
                'fontSize' => array('Desktop' => '14px', 'Tablet' => '14px', 'Mobile' => '14px'),
                'fonts' => array(),
                'letterCase' => array(),
                'letterSpacing' => array(),
                'lineHeights' => array('Desktop' => '1.5', 'Tablet' => '1.5', 'Mobile' => '1.5'),
                'orientation' => array(),
            ),

            'contenttypography' => array(
                'appearance' => array(),
                'decoration' => array(),
                'fontSize' => array('Desktop' => '14px', 'Tablet' => '14px', 'Mobile' => '14px'),
                'fonts' => array(),
                'letterCase' => array(),
                'letterSpacing' => array(),
                'lineHeights' => array('Desktop' => '1.5', 'Tablet' => '1.5', 'Mobile' => '1.5'),
                'orientation' => array(),
            ),
            'horigap' => array(
                'Desktop' => array('left' => 'var:preset|vayu-blocks-spacing|20'),
                'Tablet' => array('left' => 'var:preset|vayu-blocks-spacing|20'),
                'Mobile' => array('left' => 'var:preset|vayu-blocks-spacing|20'),
            ),
            'vergap' => array(
                'Desktop' => array('top' => 'var:preset|vayu-blocks-spacing|20'),
                'Tablet' => array('top' => 'var:preset|vayu-blocks-spacing|20'),
                'Mobile' => array('top' => 'var:preset|vayu-blocks-spacing|20'),
            ),
            'spacing' => array(
                'Desktop' => 6,
                'Tablet' => 6,
                'Mobile' => 6,
            ),
            'categorytypography' => array(
                'appearance' => array(),
                'decoration' => array(),
                'fontSize' => array('Desktop' => '13px', 'Tablet' => '13px', 'Mobile' => '13px'),
                'fonts' => array(),
                'letterCase' => array(),
                'letterSpacing' => array(),
                'lineHeights' => array('Desktop' => '1', 'Tablet' => '1', 'Mobile' => '1'),
                'orientation' => array(),
            ),
            'categoryradius' => array(
                'Desktop' => array(
                    'topLeft' => '4px',
                    'topRight' => '4px',
                    'bottomLeft' => '4px',
                    'bottomRight' => '4px',
                ),
                'Tablet' => array(
                    'topLeft' => '4px',
                    'topRight' => '4px',
                    'bottomLeft' => '4px',
                    'bottomRight' => '4px',
                ),
                'Mobile' => array(
                    'topLeft' => '4px',
                    'topRight' => '4px',
                    'bottomLeft' => '4px',
                    'bottomRight' => '4px',
                ),
            ),
            'categorypadding' => array(
                'Desktop' => array(
                    'top' => '4px',
                    'right' => '4px',
                    'bottom' => '4px',
                    'left' => '4px',
                ),
                'Tablet' => array(
                    'top' => '4px',
                    'right' => '4px',
                    'bottom' => '4px',
                    'left' => '4px',
                ),
                'Mobile' => array(
                    'top' => '4px',
                    'right' => '4px',
                    'bottom' => '4px',
                    'left' => '4px',
                ),
            ),
            'tagtypography' => array(
                'appearance' => array(),
                'decoration' => array(),
                'fontSize' => array('Desktop' => '13px', 'Tablet' => '13px', 'Mobile' => '13px'),
                'fonts' => array(),
                'letterCase' => array(),
                'letterSpacing' => array(),
                'lineHeights' => array('Desktop' => '1', 'Tablet' => '1', 'Mobile' => '1'),
                'orientation' => array(),
            ),
            'tagGap' => array(
                'Desktop' => 3,
                'Tablet' => 3,
                'Mobile' => 3,
            ),
            'categoryGap' => array(
                'Desktop' => 3,
                'Tablet' => 3,
                'Mobile' => 3,
            ),
            'authortypography' => array(
                'appearance' => array(),
                'decoration' => array(),
                'fontSize' => array('Desktop' => '13px', 'Tablet' => '13px', 'Mobile' => '13px'),
                'fonts' => array(),
                'letterCase' => array(),
                'letterSpacing' => array(),
                'lineHeights' => array('Desktop' => '1', 'Tablet' => '1', 'Mobile' => '1'),
                'orientation' => array(),
            ),

);
?>
