<?php
return array(
    // Settings
        'uniqueId' => '',
        'globalwidth' => 0,
        'image' => '',
        'opacity' => 1,
        'overlaytransitiontime' => 0.5,
        'imagetransitiontime' => 0.5,
        'overlay' => false,
        'imagehvreffect' => 'none',
        'imagehvranimation' => 'none',
        'imagehvrfilter' => 'none',
        'imageoverlayouteffect' => 'none',
        'overlayhvrcolor' => '',
        
        'focalPoint' => array(
            'x' => 0.5,
            'y' => 0.5,
        ),
        'imageborderradiuscircle' => 'square',
        'imagecover' => 'cover',
        'imageaspectratio' => array(
            'Desktop' => '16/9',
            'Tablet' =>'16/9',
            'Mobile' =>'16/9'
        ),
        'duotone' => '',
        'showPreview' => false,
        'overlayalignment' => 'center center',
        'overlayalignmentvertical' => 'center',
        'overlayalignmenttablet' => 'center center',
        'overlayalignmentverticaltablet' => 'center',
        'overlayalignmentmobile' => 'center center',
        'overlayalignmentverticalmobile' => 'center',
        'rotation'=> '0',
        'endTime'=> 0,
        'rel'=>false,
        'youtubefullscreen'=> true,
        
        'animationData'=> array(
                'effect'=> array(),
                'imageAnimation'=> array(),
                'mask'=> array(),
                'hovereffect'=> array()
          ),

        'imagealignment' =>  array(
        'Desktop' => 'center',
        'Tablet' => 'center',
        'Mobile' => 'center'
        ),
        'screenfit'=> 'auto',
        'imageaspectratio' => 'original',
        'imageaspectratiotablet' => 'original',
        'imageaspectratiomobile' => 'original',
        'wrapppereffect3color' => 'white',
        'duotone'=> array(),
        'overlayshow'=>false,
        'maskshape'=> 'none',
        'masksize'=>'auto',
        'maskposition'=>'center center',
        'maskrepeat'=>'no-repeat',
        'imagealttext'=>'',
        'captiontext'=> 'Write Caption...',
        'caption'=>false,
        'captionsize'=>16,
        'captionfontweight'=> 'normal',
        'captionsizeTablet'=>16,
        'captionfontweightTablet'=> 'normal',
        'captionsizeMobile'=>16,
        'captionfontweightMobile'=> 'normal',
        'captioncolor'=>'black',
        'captionalignment'=>'center',
        'captionalignmentTablet'=>'center',
        'captionalignmentMobile'=>'center',
        'imagewidth'=>'',
        'imageheight'=>'',
        'imagewidthtablet'=>'',
        'imageheighttablet'=>'',
        'imagewidthmobile'=>'',
        'imageheightmobile'=>'',
        'overlaybordertype'=>'color',
        'overlaybordergradient'=>'linear-gradient(135deg,rgb(74,234,220) 0%,rgb(151,120,209) 20%,rgb(207,42,186) 40%,rgb(238,44,130) 60%,rgb(251,105,98) 80%,rgb(254,248,76) 100%)',
        'overlayborderimage'=>'',
        'overlayborderimagetype'=>'none',
        'overlaygradienttop'=>'5px',
        'overlaygradientbottom'=>'5px',
        'overlaygradientleft'=>'5px',
        'overlaygradientright'=>'5px',
        'overlayimagetop'=>'5px',
        'overlayimagebottom'=>'5px',
        'overlayimageleft'=>'5px',
        'overlayimageright'=>'5px',
        'overlayspace'=>'space',
        'borderimagesize'=> 30,
        'imagebackgroundSize' => 'cover',
        'overlaywidth'=>'100%',
        'borderimageoutset' => 5,
        'overlayheight'=>'100%',
        'overlaywidthtablet'=>'100%',
        'overlayheighttablet'=>'100%',
        'overlaywidthmobile'=>'100%',
        'overlayheightmobile'=>'100%',
        'overlayleft'=>'0%',
        'overlaytop'=>'0%',
        'overlaylefttablet'=>'0%',
        'overlaytoptablet'=>'0%',
        'overlayleftmobile'=>'0%',
        'overlaytopmobile'=>'0%',
        'animationsettings' => 'without-hvr',
        'wrapperanimation'=>'none',
        'overlaywrapper'=> 'none',
        'imageboxShadow'=> array(),
        'animationhover' => true,
        'frameshow'=>false,
        'overlayopacity' => 0.5,
        'startTime' => 0,
        'typeimage'=>'video',
        'videoUrl'=>'',
        'autoplay'=>true,
        'loop'=>true,
        'controls'=>true,
        'muted'=>true,
        'fallbackImageUrl'=>'',
        'nofullscreen'=> false,
        'nodownload'=> false,
        'noremoteplayback'=> false,
        'noplaybackrate'=> false,
        'blockValue'=>'',
        'youvideoUrl'=>'',
        'heightvideosize'=>300,
        'youautoplay'=> true,
        'youloop'=> true,
        'youcontrols'=>'true',
        'stratTime' => 0,
        'contentani' => true,
        'vimeourl'=>'',
        'vimeoautoplay'=>false,
        'vimeomuted'=>false,
        'vimeoloop'=>false,
        'vimeocontrols'=>true,
        'vimeobackground'=>false,
        'vimeocolor'=>'00adef',
        'vimeofullscreen'=>true,

        'videoheight' => array(
            'Desktop' => '315px',
            'Tablet'  => '315px',
            'Mobile'  => '315px'
        ),
        'videowidth' => array( 
            'Desktop' => '560px',
            'Tablet'  => '560px',
            'Mobile'  => '560px'
        ),
        'youtubeshorts' => false,
        
        'posterOn'=>false,
        'poimage'=>'',
        'pofocalPoint'=> array(
            'x'=> 0.5,
            'y'=> 0.5,
        ),
        'lightbox'=>false,
        'pooverlaycolor' => 'transparent',
        'pooverlayopacity' => 0.5,
        'lightboxcolor' => '',

        'cancelcolor'=>'',
        'cancelbg'=>'white',
        'cancelcolorhover'=>'',
        'cancelbghover'=> '',
        'cancelSize' => array(
            'Desktop' => '30px',
            'Tablet' => '30px',
            'Mobile' => '30px',
        ),
);
?>
