<?php
require_once VAYU_BLOCKS_DIR_PATH . 'inc/admin/option-panel.php';
require_once VAYU_BLOCKS_DIR_PATH . 'inc/admin/register-blocks.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/admin/function.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/admin/functions-style.php';
require_once VAYU_BLOCKS_DIR_PATH . 'inc/admin/admin-api.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/admin/render-style.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/admin/update-style.php';
// render block include files
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/style/responsive-style.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/advance-animation/class-blocks-animation.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/advance-heading/advance-heading.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/advance-container/advance-container.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/advance-container/advance-container-render.php';

require_once VAYU_BLOCKS_DIR_PATH .'inc/render/advance-spacer/advance-spacer.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/advance-button/advance-button.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/advance-product-tab/advance-product-tab.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/advance-product-tab/advance-product-tab-style.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/advance-query-loop/advance-query-loop.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/wrapper/wrapper.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/vayu-sites/vayu-sites.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/post-grid/post-grid.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/post-grid/post-grid-style.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/advance-slider/advance-slider.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/advance-slider/advance-slider-style.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/flip-box/flip-box.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/image/image.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/video/video.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/flip-wrapper/flip-wrapper.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/flip-wrapper/flip-wrapper-style.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/flip-box/flip-box-style.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/image/image-style.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/video/video-style.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/icon/icon.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/icon/icon-style.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/blurb/blurb.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/blurb/blurb-style.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/unfold/unfold.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/unfold/unfold-style.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/post-pagination/post-pagination.php';

require_once VAYU_BLOCKS_DIR_PATH .'inc/render/timeline-child/timeline-child.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/timeline-child/timeline-child-style.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/advance-timeline/advance-timeline.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/advance-timeline/advance-timeline-style.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/image-hotspot/image-hotspot.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/pin-child/pin-child.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/pin-child/pin-child-style.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/swipe-slider/swipe-slider.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/swipe-slider/swipe-slider-style.php';
require_once VAYU_BLOCKS_DIR_PATH .'inc/render/slide-item/slide-item.php';