<?php
return array(
    // Settings
        'uniqueId' => '',
        'globalwidth' => 0,
        'timelinelayout' => 'layout-3',
        'boxalignment' => 'center center',
        'boxalignmentmobile' => 'center',
        'boxalignmenttablet' => 'center center',
        'boxcolor' => '#EEEEEE',
        'boxhvrcolor' => '#EEEEEE',
        'iconcolor' => '#F1E3FF',
        'iconhvrcolor' => '#6C34C7',
        'touch' => 'scroll',
        'iconiconcolor' => 'black',
        'iconiconhvrcolor' => 'white',
        'connectorcolor' => '#F1E3FF',
        'connectorhvrcolor' => '#6C34C7',
        'thickness' => 3,
        'iconsize' => 18,
        'boxpadding' => [
            'top' => '0px',
            'right' => '0px',
            'bottom' => '0px',
            'left' => '0px'
        ],
        'boxmargin' => [
            'top' => '0px',
            'right' => '0px',
            'bottom' => '0px',
            'left' => '0px'
        ],
        'datealignment' => 'center center',
        'datealignmentmobile' => 'center center',
        'datealignmenttablet' => 'center center',
        'iconalignment' => 'center',
        'iconalignmentmobile' => 'center',
        'iconalignmenttablet' => 'center',
        'datecolor' => 'gray',
        'datehvrcolor' => 'gray',
        'headingfont' => 'default',
        'headingsize' => 18,
        'headinglineHeight' => 1,
        'headingappearance' => '700',
        'headingletterSpacing' => '2px',
        'headingcolor' => 'gray',
        'headinghvrcolor' => 'gray',
        'parafont' => 'default',
        'parasize' => 18,
        'paralineHeight' => 1,
        'paraappearance' => '700',
        'paraletterSpacing' => '2px',
        'paracolor' => 'gray',
        'parahvrcolor' => 'gray',
        'showdate' => true,
        'iconName' => 'wordpress-calendar',
        'printedIcon' => '',
        'connector_top'=> '',
        'connector_left'=> '',
        'connector_height' => '',
        'connector_bottom'=>'',
        'final_connector_top'=>0,
        'final_connector_left'=>0,
        'final_connector_height'=> 0,
        'iconHeight'=> 0,
        'final_connector_width'=> 0,
        'layouttype' => 'vertical',
        'datebackgroundcolorhvr' => '',
        'datebackgroundcolor' => '',
        'connector' => true,
        'totalHeightback' => 0,
        'thicknessTablet'=>3,
        'iconsizeTablet'=>18,
        'thicknessMobile'=>3,
        'iconsizeMobile'=>18,
        'scrollbarwidth'=>'4px',
        'scrollbarheight'=>'4px',
        'thumbbg'=>'#6C34C7',
        'thumbbghvr'=>'',
        'trackbg'=>'#F1E3FF',
        'gapchild'=> array(
            'Desktop'=>6,
            'Tablet'=>6,
            'Mobile'=>6
        ),
);
?>
