<?php
return array(
    // edit.json
        'index' => 0,
        'uniqueId' => '',
        'autoplay' => false,
        'navigation' => true,
        'pagination' => true,
        'selectedFoldIcon' => 'none',
        'centeredSlides' => false,
        'grabCursor' => false,
        'initialSlide' => 1,
        'simulateTouch' => false,
        'loop' => true,
        'slidesPerView' => 1,
        'spaceBetween' => 10,
        'freeMode' => false,
        'mousewheel' => false,
        'delay' => 500,
        'disableOnInteraction' => true,
        'pauseOnMouseEnter'=>true,
        'reverseDirection'=>false,
        'stopOnLastSlide'=>false,
        'effect' => 'none',
        'scrollbar' => false,
        'dynamicBullets' => false,
        'dynamicMainBullets' => 1,
        'slideslength' => 0,
        'scrollBox' => 'rgba(0, 0, 0, .1)',
        'scroll' => '#00000063',
        'scrolltop' => 98,
        'scrollheight' => 6,
        'scrollerheight' => 6,
        'navigationbackground' => '',
        'navigationcolor' => '#000000',
        'navigationsize' => 25,
        'navigationtop' => 46,
        'rightarrow' => 11,
        'leftarrow' => 14,
        'advanceRadiusglobal'=> [
            'top'=> '4px',
            'bottom'=> '4px',
            'left'=> '4px',
            'right'=> '4px'
        ],
        'advanceborderglobal'=> [
            'topcolor'=> '',
            'topwidth'=> '0px',
            'topstyle'=> 'solid',
            'bottomcolor'=> '',
            'bottomwidth'=> '0px',
            'bottomstyle'=> 'solid',
            'leftcolor'=> '',
            'leftwidth'=> '0px',
            'leftstyle'=> 'solid',
            'rightcolor'=> '',
            'rightwidth'=> '0px',
            'rightstyle'=> 'solid'
        ],

        'arrowborder'=> array(),
        'arrowborderradius'=> array(),
        'arrowpadding'=> array(),
    
        'advancebordertype'=> 'color',
        'advancebordergradient'=> 'linear-gradient(135deg,rgb(74,234,220) 0%,rgb(151,120,209) 20%,rgb(207,42,186) 40%,rgb(238,44,130) 60%,rgb(251,105,98) 80%,rgb(254,248,76) 100%)',
        'advancegradienttop'=> '5px',
        'advancegradientbottom'=> '5px',
        'advancegradientleft'=> '5px',
        'advancegradientright'=> '5px',
    
        'advanceimagetop'=> '5px',
        'advanceimagebottom'=> '5px',
        'advanceimageleft'=> '5px',
        'advanceimageright'=> '5px',
    
        'advanceborderimagetype'=> 'none',
        'advanceborderimage'=> '',
    
        'advancespace'=> 'space',
    
        'advanceborderimagesize'=> 30,
    
        'advanceborderimageoutset'=> 5,
    
        'advancegradientborderimageoutset'=> 5,
    
        'boxShadowglobal'=> false,
    
        'boxShadowColorglobal'=> '',
    
        'boxShadowColorOpacityglobal'=> 50,
    
        'boxShadowBlurglobal'=> 5,
    
        'boxShadowSpreadglobal'=> 1,
    
        'boxShadowHorizontalglobal'=> 0,
    
        'boxShadowVerticalglobal'=> 0,

        'paginationbackground' => 'blue',
        'paginationinactivebackground' => '#070ae378',
        'paginationtop' => 85,
        'bulletsize' => 10,
        'numberscolor' => 'black',
        'dotsplace' => 50,
        'progresscolor' => 'blue',
        'progresshover' => false,
        'navigationtype'=>'default',
        'dotstype' => 'default',
        'initialSlideTablet' => 1,
        'initialSlideMobile' => 1,
        'slidesPerViewTablet'=> 1,
	    'slidesPerViewMobile'=> 1,
        'spaceBetweenTablet'=> 10,
        'spaceBetweenMobile'=> 10,
        'navigationbackgroundTablet'=>'#abb7c2bf',
        'navigationbackgroundMobile'=>'#abb7c2bf',
        'navigationsizeTablet'=>25,
	    'navigationsizeMobile'=>25,
        'navigationtopTablet'=>46,
        'navigationtopMobile'=>46,
        'rightarrowTablet'=>11,
        'rightarrowMobile'=>11,
        'paginationtopTablet'=>85,
        'paginationtopMobile'=>85,
        'bulletsizeTablet'=>10,
        'bulletsizeMobile'=>10,
        'dotsplaceTablet'=>50,
        'dotsplaceMobile'=>50,
        'arrowradius' => array(
            'top' => '4px',
            'bottom' => '4px',
            'left' => '4px',
            'right' => '4px',
        ),
        'arrowradiusTablet' => array(
            'top' => '4px',
            'bottom' => '4px',
            'left' => '4px',
            'right' => '4px',
        ),
        'arrowradiusMobile' => array(
            'top' => '4px',
            'bottom' => '4px',
            'left' => '4px',
            'right' => '4px',
        ),
        'arrowTopborderType'=>'solid',
        'arrowBottomborderType'=>'solid',
        'arrowLeftborderType'=>'solid',
        'arrowRightborderType'=>'solid',
        'arrowTopBorder' => '0px',
        'arrowBottomBorder' => '0px',
        'arrowLeftBorder' => '0px',
        'arrowRightBorder' => '0px',
        'arrowTopBorderColor' => 'blue',
        'arrowBottomBorderColor' => 'blue',
        'arrowLeftBorderColor' => 'blue',
        'arrowRightBorderColor' => 'blue',
        'arrowBottomborderTypeTablet'=>'solid',
        'arrowLeftborderTypeTablet'=>'solid',
        'arrowRightborderTypeTablet'=>'solid',
        'arrowTopBorderTablet' => '0px',
        'arrowBottomBorderTablet' => '0px',
        'arrowLeftBorderTablet' => '0px',
        'arrowRightBorderTablet' => '0px',
        'arrowTopBorderColorTablet' => 'blue',
        'arrowBottomBorderColorTablet' => 'blue',
        'arrowLeftBorderColorTablet' => 'blue',
        'arrowRightBorderColorTablet' => 'blue',
        'arrowBottomborderTypeMobile'=>'solid',
        'arrowLeftborderTypeMobile'=>'solid',
        'arrowRightborderTypeMobile'=>'solid',
        'arrowTopBorderMobile' => '0px',
        'arrowBottomBorderMobile' => '0px',
        'arrowLeftBorderMobile' => '0px',
        'arrowRightBorderMobile' => '0px',
        'arrowTopBorderColorMobile' => 'blue',
        'arrowBottomBorderColorMobile' => 'blue',
        'arrowLeftBorderColorMobile' => 'blue',
        'arrowRightBorderColorMobile' => 'blue',

);
?>